#!/bin/bash

case "$1" in
	start)			
			python umnyy-car.py >logs/umnyy-car.log 2>&1 & echo $! >logs/umnyy-car.pid
			python humidity-temperature.py >logs/humidity-temperature.log 2>&1 & echo $! >logs/humidity-temperature.pid
			python distance.py >logs/distance.log 2>&1 & echo $! >logs/distance.pid
			
			sudo motion
		;;
	stop)
			pid=$(cat logs/umnyy-car.pid)
			echo Close main program $pid
			kill $pid
			echo -1 > logs/umnyy-car.pid
			
			pid=$(cat logs/humidity-temperature.pid)
			echo Close humidity and temperature $pid
			kill $pid
			echo -1 > logs/humidity-temperature.pid

			pid=$(cat logs/distance.pid)
			echo Close distance sensor $pid
			kill $pid
			echo -1 > logs/distance.pid
			
			sudo killall motion
		;;
	*)
		echo $"Usage: $0 {start|stop}"
	exit 1
esac
